config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'activities#select_activity'
  get 'activities/select_activity'
  get 'activities/earning_student'
  
  get 'activities/cash_out'
  
  get 'activities/show'
  
  get 'activities/destroy/:id' => 'activities#destroy'
  
  post 'activities' => 'activities#new'

  resources :activities do
  get 'generatecode', action: :generatecode, controller: 'activities'
  end
  

  
  

end

app/models/activity.rb
#this is the activity model
class Activity < ActiveRecord::Base
end

app/models/user.rb
#this is the user model
#it enforces the compensation limit and handles certain elements of devise
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  

  attr_reader :compensation
  def set_compensation(new_compensation)
    compensation_limit = 500
    if new_compensation > compensation_limit
      @compensation = compensation_limit
    else
      @compensation = new_compensation
    end
  end


end

app/controllers/activities_controller.rb
#this is the activites controller
class ActivitiesController < ApplicationController

  def activities_params
    params.require(:activity).permit(:title, :duration, :startTime, :description, :activeCode)
  end

  def show
    #@work = Work.find(params[:id])
    #id = params[:id] # retrieve activities ID from URI route
    #@activity = Activity.find(id) # look up activities by unique ID
    # will render app/views/activities/show.<extension> by default
    
    @activity = Activity.find(params[:id]) # look up activities by unique ID
    if (params[:textinput] != nil)
     @activity.update(:activeCode => params[:textinput]) #updates activeCode with the 'save button'
    end
   
    
  end

  def index
   # @activities = Activity.all
    
  end

  def new
    # default: render 'new' template
  end

  def create
    @prng = Random.new
    @activities_params_copy = activities_params.merge(:activeCode => @prng.rand(1000000))
    if (activities_params[:title] == "")
      flash[:notice] = "Activity could not be created."
      redirect_to('/activities/select_activity') and return
    else
      @activity = Activity.create!(@activities_params_copy)
      flash[:notice] = "#{@activity.title} was successfully created."
      redirect_to("/activities/" + @activity.id.to_s) and return
    end
  end

  def edit
    @activity = Activity.find params[:id]
  end

  def update
   @prng = Random.new
   @activities_params_copy = activities_params.merge(:activeCode => @prng.rand(1000000))
   @activity = Activity.find params[:id]
   @activity.update(activities_params)
   flash[:notice] = "#{@activity.title} was successfully created."
   redirect_to "/activities/" + @activity.id.to_s
  end
  
  def generatecode
   @prng = Random.new
   @newCode = @prng.rand(1000000)
   @activity = Activity.find params[:activity_id]
   @activity.update(:activeCode => @newCode)
   flash[:notice] = "A new code for #{@activity.title} was successfully generated."
   redirect_to "/activities/" + @activity.id.to_s
  end
  
  def destroy
    @activities = Activity.find(params[:id])
    @activities.destroy
    flash[:notice] = "Activity '#{@activities.title}' deleted."
    #redirect_to activities_path
    redirect_to "/activities/select_activity"
  end
  
  #added this to display select activity page since it had no controller connected to it
  #I just copied the html file to the Backup folder under root of the workspaceand 
  #now works if you add /activities/select_activity to url
  def select_activity
    @activities = Activity.all
  end
  
  def earning_student
    #get current user
    #current user gets parsed by some regex in the corresponing view
    #im not sure what I would write as a test for this literal single line of code
    @current_user_data = current_user
    #@bool = @current_user_data.respond_to?(:to_s)
  end
  
  def cash_out
  end

end

app/controllers/application_controller.rb
#this is the application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception
  

end

app/views/activities/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Activity

= form_tag activity_path(@activity), :method => :put do

  = label :activity, :title, 'Title'
  = text_field :activity, 'title'
  
  = label :activity, :description, 'Description'
  = text_field :activity, 'description'

  = label :activity, :duration, 'Duration'
  = select :activity, :duration, [60, 75, 120, 155]

  = label :activity, :startTime, 'Start Time'
  = datetime_select :activity, :startTime

  = submit_tag 'Update Activity Info'

app/views/activities/index.html.haml
-#  This file is app/views/activities/index.html.haml
%h1 Select Activity

%table#activities
  %thead
    %tr
      %th Activity Title
      %th Start Time
      %th Duration
      %th More Info
  %tbody
    - @activities.each do |activity|
      %tr
        %td= activity.title 
        %td= activity.startTime
        %td= activity.duration
        %td= link_to "More about #{activity.title}", activity_path(activity)

= link_to 'Add new activity', new_activity_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Cash For Class
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title BootStrap the CDN way
    / CSS and stuff from boot strap link
    %link{:crossorigin => "anonymous", :href => "app/assets/stylesheets/bootstrap.css", :integrity => "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", :rel => "stylesheet"}/
    / do not use default.css, simply go into bootstrap.css to change or add any css elements. If you use both, it gets conflicted and does not do css
    %script{:crossorigin => "anonymous", :integrity => "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"}

%body
  %div{:style => "text-align: center"}
    %img{:src => "https://preview.ibb.co/g1fqa7/Logo2.png", :style => "width:500px;height:90px;margin-top:10px"}
  %br
    %div
      - if user_signed_in?
        %nav.navbar.navbar-default{role: "navigation"} 
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Menu
                %b.caret
              %ul.dropdown-menu
                %li
                  =link_to "Home", root_path
                %li
                  =link_to "Student Earning", activities_earning_student_path
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{href: "/users/sign_out"} Log Out
  %div{:style => "text-align: center"}  
    =yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 Select Activity

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name)%><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>